spring.application.name=electo

# ===============================
# PostgreSQL / Neon Database
# ===============================
spring.datasource.url=jdbc:postgresql://ep-lingering-lake-b4qx3m59-pooler.c-6.us-east-2.aws.neon.tech:5432/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_Pd07VqYltLIN

# ===============================
# JPA / Hibernate
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true

# ===============================
# Resend
# ===============================
# resend.api.key=${RESEND_API_KEY}

# =============================== 
# OTP Configuration 
# =============================== 
# otp.expiry.minutes=5