spring.application.name=electo

# ===============================
# PostgreSQL / Neon Database
# ===============================
spring.datasource.url=jdbc:postgresql://ep-lingering-lake-b4qx3m59-pooler.c-6.us-east-2.aws.neon.tech:5432/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_Pd07VqYltLIN

# ===============================
# JPA / Hibernate
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true

# Gmail SMTP Configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=daegnamangu10a@gmail.com
spring.mail.password=zecg nhzm cdwt xmvk
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true