spring.datasource.url=jdbc:mysql://localhost:3306/electo
spring.datasource.username=electo_user
spring.datasource.password=06012008

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Gmail SMTP Configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=daegnamangu10a@gmail.com
spring.mail.password=zecg nhzm cdwt xmvk
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true